import { v4 as uuidv4 } from 'uuid';

export const sampleCards = [
  {
    id: uuidv4(),
    playerName: 'Joe Namath',
    year: '2023',
    brand: 'Panini',
    setName: 'Kaboom',
    cardNumber: '',
    variant: 'Kaboom Insert',
    category: 'football',
    team: 'New York Jets',
    condition: 'raw',
    grade: null,
    tags: ['Insert', 'Kaboom'],
    purchasePrice: 150,
    currentValue: 250,
    purchaseDate: '2024-06-15',
    dateAdded: '2024-06-15T10:00:00Z',
    notes: 'Iconic Kaboom insert with holographic background. Beautiful card of Broadway Joe.',
    serialNumber: '',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    playerName: 'Dak Prescott / Ezekiel Elliott',
    year: '2018',
    brand: 'Panini',
    setName: 'Immaculate Collection',
    cardNumber: '24',
    variant: 'Dual Jerseys Prime Gold',
    category: 'football',
    team: 'Dallas Cowboys',
    condition: 'bgs',
    grade: '9',
    gradeSubgrades: { centering: '10', corners: '9.5', edges: '9.5', surface: '8.5' },
    tags: ['Patch', 'Numbered'],
    purchasePrice: 200,
    currentValue: 350,
    purchaseDate: '2024-03-20',
    dateAdded: '2024-03-20T14:30:00Z',
    notes: 'BGS 9 Mint. Dual jersey patch /20. Prime Gold parallel with beautiful patch windows.',
    serialNumber: '07/20',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    playerName: 'Tua Tagovailoa',
    year: '2020',
    brand: 'Panini',
    setName: 'Donruss Optic',
    cardNumber: '152',
    variant: 'Holo',
    category: 'football',
    team: 'Miami Dolphins',
    condition: 'psa',
    grade: '10',
    tags: ['Rookie', 'Holo', 'Optic'],
    purchasePrice: 80,
    currentValue: 120,
    purchaseDate: '2024-01-10',
    dateAdded: '2024-01-10T09:15:00Z',
    notes: 'PSA 10 Gem Mint. Rated Rookie Holo parallel. Cert #61073045.',
    serialNumber: '',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    playerName: 'Rashee Rice',
    year: '2023',
    brand: 'Panini',
    setName: 'National Treasures',
    cardNumber: '',
    variant: 'RPA',
    category: 'football',
    team: 'Kansas City Chiefs',
    condition: 'raw',
    grade: null,
    tags: ['Rookie', 'Auto', 'Patch', 'RPA', 'Numbered'],
    purchasePrice: 300,
    currentValue: 275,
    purchaseDate: '2024-04-05',
    dateAdded: '2024-04-05T16:45:00Z',
    notes: 'National Treasures Rookie Patch Auto /99. Jersey swatch with on-card auto from SMU.',
    serialNumber: '68/99',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    playerName: 'Malik Nabers',
    year: '2024',
    brand: 'Panini',
    setName: 'Donruss Optic',
    cardNumber: '271',
    variant: 'Orange Scope',
    category: 'football',
    team: 'New York Giants',
    condition: 'psa',
    grade: '9',
    tags: ['Rookie', 'Refractor', 'Optic', 'Numbered'],
    purchasePrice: 175,
    currentValue: 225,
    purchaseDate: '2025-01-15',
    dateAdded: '2025-01-15T11:20:00Z',
    notes: 'PSA 9 Mint. Rated Rookie Orange Scope parallel. Stunning holographic pattern. Cert #124288403.',
    serialNumber: '',
    imageUrl: '',
  },
];

export const sampleValueHistory = [
  { date: '2024-01', value: 480 },
  { date: '2024-02', value: 510 },
  { date: '2024-03', value: 720 },
  { date: '2024-04', value: 980 },
  { date: '2024-05', value: 950 },
  { date: '2024-06', value: 1150 },
  { date: '2024-07', value: 1100 },
  { date: '2024-08', value: 1050 },
  { date: '2024-09', value: 1120 },
  { date: '2024-10', value: 1080 },
  { date: '2024-11', value: 1150 },
  { date: '2024-12', value: 1100 },
  { date: '2025-01', value: 1220 },
];
